eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/
server:
  port: 8802
spring:
  application:
    name: eureka-client
