eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8813
spring:
  application:
    name: ribbon-user-provider
