eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8801/eureka/
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        statusPageUrlPath: ${server.servletPath}/info
        healthCheckUrlPath: ${server.servletPath}/health
server:
  port: 8801
spring:
  application:
    name: eureka-server
